language: python
matrix:
  include:
  - os: linux
    dist: xenial
    python: 3.5
    env: TOXENV=py35
  - os: linux
    dist: xenial
    python: 3.6
    env: TOXENV=py36
  - os: linux
    dist: xenial
    python: 3.7
    env: TOXENV=py37,black,docs
  - os: osx
    language: generic
install:
- chmod +x .travis/install.sh
- "./.travis/install.sh"
script:
- chmod +x .travis/test.sh
- "./.travis/test.sh"
after_success:
- codecov
deploy:
  provider: pypi
  user: lwasser
  password:
    secure: d9dDnd2TzD3+LypV6WxQLRBRMZ092tuNyv0VxXLXpxbfCPM/Wiv6nmM89siEYBvil91AxNgzsCkjwLu5ybpsBNntprZGo2eFGteYhaVQRIlmPosPH9twgxg2lAmPYpPSiqeDMEAlSblI1+vCOumvY0uG7KcP9FzHxAt6L/daPE2kXidmhQhA6taAD7OOr30RjDXjjdnnMhFATqzJR2inCCCnqnAh376H0HxdanS5vz0lECjIPyY2yrIkPz/0wSLZD+hTzqM3oL74uIa+poGVGrnJgBIj42DBVOcxEiamSLTfUDWWVrN7bMIMkgHEZqTm3QzdCy5QxEanF2paaBiGFTc1EVP13P+l5Ld6l8owb5/Z6JBtM3XJuB5gK9ysOQLW36ZqDmCn2zqLdSBpv4InScJTu0sQvSbMW0W32iLlc3MJ3Eu6VsxuTk300EBPetAy2rKbgEi5xO7C6TjhpwKUGm515NK026VAJvGCT9rQebBzEtCSVHKVuqjSt0S9QkrDdNTYK0h/O/5eYscORnsZ/kfXwuxgnOUV/apk1iFv7yfVGxz4mnOvrdbXuySKIsL/fmYT35u86gi1ugFNsmJGOe6LBT1rAocFCMpAQYgj5Gn/uQpIlbibgFZa4ElfjXPHvBTxK+ZX+rkS3GLaLnObhrqIEw6H/ak1DpF9rYx1qxs=
  on:
    tags: true
    repo: earthlab/matplotcheck
    python: 3.6
