language: python
matrix:
  include:
  - os: linux
    dist: xenial
    python: 3.5
    env: TOXENV=py35
  - os: linux
    dist: xenial
    python: 3.6
    env: TOXENV=py36
  - os: linux
    dist: xenial
    python: 3.7
    env: TOXENV=py37,black,docs
  - os: osx
    language: generic
install:
- chmod +x .travis/install.sh
- "./.travis/install.sh"
script:
- chmod +x .travis/test.sh
- "./.travis/test.sh"
after_success:
- codecov
deploy:
  provider: pypi
  user: lwasser
  password:
    secure: RQP5MLtrhgZZnHgJIVe7LGNU8DfhB9AVS5B5sh0H9SEqTDcHbeq0ik2Uh+l5C4Ak6A24Q+rsAU2PlFnr2Eq2Afx3gogT3uzalJv6fmPe+wsnNJMh7j60MaFU4Y2ymYdHeSALEL1/FSiX5y5ZO+h4Njfe/Xj11WEzxpmAwaqETiol5nikNTQfvstqp8MUnw7mEPw6YJLjiZIlOMbfod843bToz6ABRPq4mTfnBo8jz3p41ZPB+nQ24TJ94zC07LvJyBSCUpcQdd/s9WqlgHXO4VX2U9BAEdFu4hpFM//0ieBQpmcNj4ttYQiuFQqZq4yt2/HBenXZ9maLGadQbAmGMPjzQ0hQkdzP6tiKhMkB57DqrxbGEEDIZUvOkXnrmLu14PPTzYk38oaN5G5xNiYZu3OzjyPaeTqg5kK7FwzoTDNhuD4Otq7GkBK/hEdktFReTzNxALVdDwua6XDkXubG9Vp+z0Yhm8AwAuoeqeXS6I/DU9ihVtCU1jr4iWvFMhf4qaU1I9BTr4GNquqp0nehkm2mRmMr81x0L23owTV60sPkbT63aje3x7mHO8UroN5tkl/B08mhQu6JEfQwi1qDzr//i8ccu/rc3aWW43bx7WwOgf26BTeLwOW3MWugvwbc5epGsJ2fBI+Egnry6qnqjg7gJc7nA4XzV4dK23XZBkU=
  on:
    tags: true
    repo: earthlab/matplotcheck
    python: 3.6
