language: python
matrix:
  include:
  - os: linux
    dist: xenial
    python: 3.5
    env: TOXENV=py35
  - os: linux
    dist: xenial
    python: 3.6
    env: TOXENV=py36
  - os: linux
    dist: xenial
    python: 3.7
    env: TOXENV=py37,black,docs
  - os: osx
    language: generic
install:
- chmod +x .travis/install.sh
- "./.travis/install.sh"
script:
- chmod +x .travis/test.sh
- "./.travis/test.sh"
after_success:
- codecov
deploy:
  provider: pypi
  user: lwasser
  password:
    secure: imOBXR7U5VDOUZ9g4ZdMVl1ybO/bn2eHODHO6Fh2nAD9YoQ09njbNoS3nPgih5l1mCU3SW40d9t1OuEQ26qthHCt4U+AVm/BVjdMmC/qe2et4spf8ITmUd+AasiduvTsrnevsQMgzEHAEXhPTVSD+ZO2+0MqH/2Z9YHi+yzhMYFbw0HZSp0qnm837jtQQwjEwtX61BxWnB5Shdoqg8BKIzT1Hv0ME7sj/Ho4Q0Zh2YfHD+0mGGET0QQjMfI+0Xhql+D63n0W3JG6dPT/UPNAx/ywgqRANcrxwCKA9QRpgEg0a2gx0CZC8hD6bH182M/BVxTavJsM1GFVv+RYyHu3jy7JtIjSx0F8saHc+aAGB4UTaSeAf6YLlTXWTeSNdaPsPK6qEsAitk+Z8SkdENU2OzoPwqnBAFuXHjIhDDQb7raqNM17eUMRrSkABnD3134t87AVzZo2wA474nCUEH5h1zOvStGKP+twLKcyl7t+G2M409CAlvZ3mG7GU586DjIZU/J1SafNZ0ooNE5I7WLadvZuVhvX4hUPvfhNaD385SYI/dBtFHS0x4O8sNn96XXXAu9Bwl6Y3FuteRvY5uAT1MS0+rhJPnjBvQdcKTRhqRzENcIBetJdTpzHem1OTFhQYQEivf20ZuLnZrQRd4J4pfKnPrvj/Iof9OfOsidqdLc=
  on:
    tags: true
    repo: earthlab/matplotcheck
    python: 3.6
