name: matplotcheck-dev
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - codecov
  - numpy
  - matplotlib
  - python=3.6
  - pyqt
  - pytest
  - pytest-cov

  # Geo stuff
  - geopandas
  - rasterio
  - gdal
  - folium
