name: matplotcheck-dev
channels:
  - conda-forge
dependencies:
  # Workaround for pip 19.1 failing
  - pip=19.0.3

  # Core scientific python
  - numpy>=1.14.0
  - matplotlib>=3.0.0
  - python=3.7
  - scipy

  # Geo stuff
  - certifi
  - geopandas=0.4.1
  - rasterio=1.0.21
  - folium=0.8.3
