name: matplotcheck-dev
channels:
  - conda-forge
dependencies:

  # Core scientific python
  - numpy>=1.14.0
  - matplotlib>=3.0.0
  - python=3.7
  - scipy

  # Geo stuff
  - certifi
  - geopandas
  - rasterio
  - folium
