name: matplotcheck-dev
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - numpy
  - matplotlib=3.0.3
  - python=3.7

  # Geo stuff
  - geopandas=0.4.1
  - rasterio=1.0.21
  - folium
